spring:
  main:
    lazy-initialization: true
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://ep-shiny-credit-a59f8m6z.us-east-2.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: VQyHzsI5qbc4
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8099

jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem
  access-token:
    expiration: 60



logging:
  level:
    org.springframework.security: TRACE
