spring:
  main:
    lazy-initialization: true
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/BookingSystem
    username: postgres
    password: 1qaz!QAZ
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8099

jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem
  access-token:
    expiration: 60



# logging:
#   level:
#     org.springframework.security: TRACE
